package fluke.somelikeitdry.world;

import fluke.somelikeitdry.configs.Configs;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerDryIsland extends GenLayer
{
	public static int oceanConversionChance;
    public GenLayerDryIsland(long p_i2124_1_)
    {
        super(p_i2124_1_);
        oceanConversionChance = Configs.general.oceanConversionChance;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or Biome ID's based on the particular GenLayer subclass.
     */
    public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight)
    {
        int[] aint = IntCache.getIntCache(areaWidth * areaHeight);

        for (int i = 0; i < areaHeight; ++i)
        {
            for (int j = 0; j < areaWidth; ++j)
            {
                this.initChunkSeed((long)(areaX + j), (long)(areaY + i));
                int lando = this.nextInt(10) == 0 ? 1 : 0;
                if (lando == 0)
                	lando = this.nextInt(100) < oceanConversionChance ? 1 : 0;
                
                aint[j + i * areaWidth]  = lando;
            }
        }

        if (areaX > -areaWidth && areaX <= 0 && areaY > -areaHeight && areaY <= 0)
        {
            aint[-areaX + -areaY * areaWidth] = 1;
        }

        return aint;
    }
}